// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SistemasDistribuidos.proto

package contador;

public final class SistemasDistribuidos {
  private SistemasDistribuidos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransporteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:contador.Transporte)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 numeroInicial = 1;</code>
     */
    int getNumeroInicial();

    /**
     * <code>int32 numeroFinal = 2;</code>
     */
    int getNumeroFinal();

    /**
     * <code>int32 resutlado = 3;</code>
     */
    int getResutlado();
  }
  /**
   * Protobuf type {@code contador.Transporte}
   */
  public  static final class Transporte extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:contador.Transporte)
      TransporteOrBuilder {
    // Use Transporte.newBuilder() to construct.
    private Transporte(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transporte() {
      numeroInicial_ = 0;
      numeroFinal_ = 0;
      resutlado_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Transporte(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              numeroInicial_ = input.readInt32();
              break;
            }
            case 16: {

              numeroFinal_ = input.readInt32();
              break;
            }
            case 24: {

              resutlado_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return contador.SistemasDistribuidos.internal_static_contador_Transporte_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return contador.SistemasDistribuidos.internal_static_contador_Transporte_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              contador.SistemasDistribuidos.Transporte.class, contador.SistemasDistribuidos.Transporte.Builder.class);
    }

    public static final int NUMEROINICIAL_FIELD_NUMBER = 1;
    private int numeroInicial_;
    /**
     * <code>int32 numeroInicial = 1;</code>
     */
    public int getNumeroInicial() {
      return numeroInicial_;
    }

    public static final int NUMEROFINAL_FIELD_NUMBER = 2;
    private int numeroFinal_;
    /**
     * <code>int32 numeroFinal = 2;</code>
     */
    public int getNumeroFinal() {
      return numeroFinal_;
    }

    public static final int RESUTLADO_FIELD_NUMBER = 3;
    private int resutlado_;
    /**
     * <code>int32 resutlado = 3;</code>
     */
    public int getResutlado() {
      return resutlado_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numeroInicial_ != 0) {
        output.writeInt32(1, numeroInicial_);
      }
      if (numeroFinal_ != 0) {
        output.writeInt32(2, numeroFinal_);
      }
      if (resutlado_ != 0) {
        output.writeInt32(3, resutlado_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numeroInicial_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numeroInicial_);
      }
      if (numeroFinal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numeroFinal_);
      }
      if (resutlado_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resutlado_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof contador.SistemasDistribuidos.Transporte)) {
        return super.equals(obj);
      }
      contador.SistemasDistribuidos.Transporte other = (contador.SistemasDistribuidos.Transporte) obj;

      boolean result = true;
      result = result && (getNumeroInicial()
          == other.getNumeroInicial());
      result = result && (getNumeroFinal()
          == other.getNumeroFinal());
      result = result && (getResutlado()
          == other.getResutlado());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMEROINICIAL_FIELD_NUMBER;
      hash = (53 * hash) + getNumeroInicial();
      hash = (37 * hash) + NUMEROFINAL_FIELD_NUMBER;
      hash = (53 * hash) + getNumeroFinal();
      hash = (37 * hash) + RESUTLADO_FIELD_NUMBER;
      hash = (53 * hash) + getResutlado();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static contador.SistemasDistribuidos.Transporte parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contador.SistemasDistribuidos.Transporte parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contador.SistemasDistribuidos.Transporte parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contador.SistemasDistribuidos.Transporte parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contador.SistemasDistribuidos.Transporte parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static contador.SistemasDistribuidos.Transporte parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static contador.SistemasDistribuidos.Transporte parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static contador.SistemasDistribuidos.Transporte parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static contador.SistemasDistribuidos.Transporte parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static contador.SistemasDistribuidos.Transporte parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(contador.SistemasDistribuidos.Transporte prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code contador.Transporte}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:contador.Transporte)
        contador.SistemasDistribuidos.TransporteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return contador.SistemasDistribuidos.internal_static_contador_Transporte_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return contador.SistemasDistribuidos.internal_static_contador_Transporte_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                contador.SistemasDistribuidos.Transporte.class, contador.SistemasDistribuidos.Transporte.Builder.class);
      }

      // Construct using contador.SistemasDistribuidos.Transporte.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        numeroInicial_ = 0;

        numeroFinal_ = 0;

        resutlado_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return contador.SistemasDistribuidos.internal_static_contador_Transporte_descriptor;
      }

      public contador.SistemasDistribuidos.Transporte getDefaultInstanceForType() {
        return contador.SistemasDistribuidos.Transporte.getDefaultInstance();
      }

      public contador.SistemasDistribuidos.Transporte build() {
        contador.SistemasDistribuidos.Transporte result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public contador.SistemasDistribuidos.Transporte buildPartial() {
        contador.SistemasDistribuidos.Transporte result = new contador.SistemasDistribuidos.Transporte(this);
        result.numeroInicial_ = numeroInicial_;
        result.numeroFinal_ = numeroFinal_;
        result.resutlado_ = resutlado_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof contador.SistemasDistribuidos.Transporte) {
          return mergeFrom((contador.SistemasDistribuidos.Transporte)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(contador.SistemasDistribuidos.Transporte other) {
        if (other == contador.SistemasDistribuidos.Transporte.getDefaultInstance()) return this;
        if (other.getNumeroInicial() != 0) {
          setNumeroInicial(other.getNumeroInicial());
        }
        if (other.getNumeroFinal() != 0) {
          setNumeroFinal(other.getNumeroFinal());
        }
        if (other.getResutlado() != 0) {
          setResutlado(other.getResutlado());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        contador.SistemasDistribuidos.Transporte parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (contador.SistemasDistribuidos.Transporte) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numeroInicial_ ;
      /**
       * <code>int32 numeroInicial = 1;</code>
       */
      public int getNumeroInicial() {
        return numeroInicial_;
      }
      /**
       * <code>int32 numeroInicial = 1;</code>
       */
      public Builder setNumeroInicial(int value) {
        
        numeroInicial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numeroInicial = 1;</code>
       */
      public Builder clearNumeroInicial() {
        
        numeroInicial_ = 0;
        onChanged();
        return this;
      }

      private int numeroFinal_ ;
      /**
       * <code>int32 numeroFinal = 2;</code>
       */
      public int getNumeroFinal() {
        return numeroFinal_;
      }
      /**
       * <code>int32 numeroFinal = 2;</code>
       */
      public Builder setNumeroFinal(int value) {
        
        numeroFinal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numeroFinal = 2;</code>
       */
      public Builder clearNumeroFinal() {
        
        numeroFinal_ = 0;
        onChanged();
        return this;
      }

      private int resutlado_ ;
      /**
       * <code>int32 resutlado = 3;</code>
       */
      public int getResutlado() {
        return resutlado_;
      }
      /**
       * <code>int32 resutlado = 3;</code>
       */
      public Builder setResutlado(int value) {
        
        resutlado_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 resutlado = 3;</code>
       */
      public Builder clearResutlado() {
        
        resutlado_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:contador.Transporte)
    }

    // @@protoc_insertion_point(class_scope:contador.Transporte)
    private static final contador.SistemasDistribuidos.Transporte DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new contador.SistemasDistribuidos.Transporte();
    }

    public static contador.SistemasDistribuidos.Transporte getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transporte>
        PARSER = new com.google.protobuf.AbstractParser<Transporte>() {
      public Transporte parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Transporte(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transporte> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transporte> getParserForType() {
      return PARSER;
    }

    public contador.SistemasDistribuidos.Transporte getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contador_Transporte_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contador_Transporte_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032SistemasDistribuidos.proto\022\010contador\"K" +
      "\n\nTransporte\022\025\n\rnumeroInicial\030\001 \001(\005\022\023\n\013n" +
      "umeroFinal\030\002 \001(\005\022\021\n\tresutlado\030\003 \001(\005b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_contador_Transporte_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contador_Transporte_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contador_Transporte_descriptor,
        new java.lang.String[] { "NumeroInicial", "NumeroFinal", "Resutlado", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
